Repository tidyblocks/tidyblocks, pull requests merged in 2020-08, with the labels that each got.

#341 Adding language lookup for toolbox category names
  blocks/blocks.js
  blocks/combine.js
  blocks/data.js
  blocks/helpers.js
  blocks/op.js
  blocks/plot.js
  blocks/stats.js
  blocks/transform.js
  blocks/value.js
  index.js
Labels: feature

#345 Removing national flags.
  index.html
  index.md
  static/flags/spain.svg
  static/flags/united-kingdom.svg
Labels: bug

#361 Adding Spanish to blocks.js
  blocks/blocks.js
Labels: Spanish

#358 Update blocks.js
  blocks/blocks.js
Labels: Korean

#356 Update blocks.js
  blocks/blocks.js
Labels: Arabic

#363 Updating unnamed reports
  blocks/blocks.js
  blocks/helpers.js
  blocks/transform.js
  libs/env.js
  libs/pipeline.js
  libs/program.js
  libs/transform.js
  libs/ui/select.jsx
  libs/ui/tabs.jsx
  libs/ui/ui.jsx
  test/fixture.js
  test/test_codegen.js
  test/test_gui.js
  test/test_pipeline.js
  test/test_program.js
  test/test_restore.js
  test/test_transform.js
Labels: feature, in progress

#324 Multiple plot
  libs/ui/select.jsx
  libs/ui/tabs.jsx
  libs/ui/ui.jsx
  static/sass/base.scss
Labels: feature

#376 Checking consistency of message string translations.
  bin/check_translations.js
  blocks/blocks.js
  blocks/combine.js
  blocks/data.js
  blocks/op.js
  blocks/plot.js
  blocks/stats.js
  blocks/transform.js
  blocks/value.js
  package.json
Labels: feature

#382 Using 'SVG' instead of 'Svg' in human text.
  libs/ui/menuBar.jsx
  libs/ui/saveDialog.jsx
Labels: feature

#397 Adding numrows to protocol
  babel.config.json
  libs/dataframe.js
  libs/op.js
  libs/value.js
  test/test_op.js
  test/test_restore.js
Labels: feature

#408 Binning
  blocks/blocks.js
  blocks/transform.js
  en/img/transform_bin.svg
  en/transform.md
  libs/transform.js
  test/test_codegen.js
  test/test_transform.js
Labels: feature
